apiVersion: apps/v1
kind: Deployment
metadata:
  name: kss-mcp-template
  labels:
    app: kss-mcp-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kss-mcp-template
  template:
    metadata:
      labels:
        app: kss-mcp-template
    spec:
      containers:
      - name: kss-mcp-template
        image: docker-hosted.sebaoffice.ir/kss-mcp-template:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /sse
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /sse
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: kss-mcp-template
  labels:
    app: kss-mcp-template
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access needed
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: kss-mcp-template

